TARGET=ESP32
#TARGET?=RP2040
ifeq ($(TARGET),ESP32)
PORT=/dev/ttyUSB0
#ESP32_FILESYSTEM=littlefs
#ESP32_PSRAM=enabled
ESP32_FILESYSTEM=spiffs
ESP32_FILESYSTEM_PART=spiffs
ESP32_PARTSCHEME=min_spiffs
ESP32_FLASHSIZE=16MB
else ifeq ($(TARGET),RP2040)
PORT=/dev/ttyACM0
TARGET_BOARD=adafruit_qtpy
RP2040_FLASHSIZE=8MB
endif
GITHUB_REPOS= \
reeltwo/Reeltwo

include ../Arduino.mk
